[package]
name = "rust-media"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.19.0"
bpaf = { version = "0.7", features = ["derive", "bright-color"] }
log = "0.4.22"
env_logger = "0.11.5"
